### ISSUE TITLE
Coordinate are nil for places

### ISSUE THREAD

**Issue by Shawnees** [Raureif/WikipediaKit#3]
Hello, i made a search with this code,
        let language = WikipediaLanguage(Locale.preferredLanguages[0])
        let _ = Wikipedia.shared.requestOptimizedSearchResults(language:language, term: "Paris") { (searchResults, error) in
            
            guard error == nil else { return }
            guard let searchResults = searchResults else { return }
            
            for articlePreview in searchResults.results {
                print(articlePreview.displayTitle)
            }
        }

But the coordinate in articlePreview is always nil

**Comment by frankrausch** [comment]
You’re right. 

The reason is that the Wikipedia API only allows getting the coordinates together with the search results if you use the **full text search**, not the **prefix search**  method (as far as I know). 

Because of this inconsistency, I decided not to retrieve the coordinates in the search results at all (the `coordinate` parameter is only populated when you use the Nearby search).

I will take another look at this, but for now you could add the `coordinates` parameter to the query yourself in [Wikipedia+Search.swift](https://github.com/Raureif/WikipediaKit/blob/master/Sources/Wikipedia%2BSearch.swift) in line 169:

    "prop": "extracts|pageterms|pageimages|coordinates"

and then use

    Wikipedia.shared. requestSearchResults(method: .fullText, language: language, term: "Paris")

… instead of the optimized search (which uses both the `.fullText` and the `.prefix` search methods).
